In [6]:
import numpy as np

In [5]:
my_arr = np.arange(1000000)

In [6]:
my_list = list(range(1000000))

In [7]:
%time for _ in range(10) :my_arr2 = my_arr *2

Wall time: 54 ms


In [8]:
%time for _ in range(10) :my_list2 = [x * 2 for x in my_list]

Wall time: 1.67 s


In [9]:
data = np.random.randn(2,3) #生成服从[0,1)均匀分布的一个2x3的数组

In [11]:
data

array([[ 0.33704956,  0.41258877,  0.61253193],
       [ 0.49616807, -0.56698491, -0.59027386]])

In [10]:
data * 10

array([[ 3.37049557,  4.12588772,  6.12531931],
       [ 4.9616807 , -5.66984914, -5.9027386 ]])

In [12]:
data + data

array([[ 0.67409911,  0.82517754,  1.22506386],
       [ 0.99233614, -1.13396983, -1.18054772]])

In [14]:
data.shape  #维度

(2, 3)

In [15]:
data.dtype  #数据类型

dtype('float64')

In [13]:
data1 = [ 6 , 7.5 , 8 ,0, 1]

In [14]:
arr1 = np.array(data1) #把列表转换成数组

In [18]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [19]:
data2 = [[1, 2 , 3, 4],[5, 6, 7, 8]] #要等长

In [7]:
arr2 = np.array(data2)

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [15]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [26]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [27]:
np.empty((2,3,2))

array([[[  1.33897934e-311,   7.06889214e-314],
        [  0.00000000e+000,   1.27319747e-313],
        [  1.27319747e-313,   1.27319747e-313]],

       [[  1.27319747e-313,   1.27319747e-313],
        [  0.00000000e+000,   4.44659081e-323],
        [  2.54639495e-313,   6.42285340e-323]]])

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [31]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [32]:
arr1.dtype

dtype('float64')

In [33]:
arr2.dtype

dtype('int32')

In [35]:
arr = np.array([1, 2, 3, 4, 5])

In [36]:
arr.dtype

dtype('int32')

In [40]:
float_arr = arr.astype(np.float64) #整型转成浮点型

In [41]:
float_arr.dtype

dtype('float64')

In [42]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [43]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [44]:
arr.astype(np.int32) #浮点型转换成整型，小数会直接截断删除

array([ 3, -1, -2,  0, 12, 10])

In [48]:
num_strings = np.array(['1.25','-9.6','42'],dtype = np.string_)
#字符串数组也能直接转换成数值形式

In [49]:
num_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [50]:
int_array = np.arange(10)

In [54]:
calibers = np.array([.22, .270, .357, .380, .44, .50],dtype = np.float64)

In [57]:
int_array.astype(calibers.dtype) #将int_array转化成calibers类型

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [58]:
empty_uint32 = np.empty(8, dtype='u4')

In [59]:
empty_uint32 

array([1512051952,        631, 1467505272,        631, 1431531280,
              631, 1742697328,          0], dtype=uint32)

## Numpy数组的计算

In [62]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [63]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [65]:
arr * arr #数组直接对应数字相乘 不是矩阵的乘法

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [66]:
arr - arr 

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [67]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [69]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [70]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [72]:
arr2 > arr1 #每个元素直接做对比

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

##  数组索引和切片

In [73]:
arr = np.arange(10)

In [74]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr[5]

5

In [76]:
arr[0]

0

In [78]:
arr[5:8] #表示【5，8）左开右闭

array([5, 6, 7])

In [79]:
arr[5:8] = 12

In [80]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [81]:
arr_slice = arr[5:8]

In [82]:
arr_slice 

array([12, 12, 12])

In [85]:
arr_slice[1] = 12345 #切片数组的变化 也会导致原始数组的变化

In [86]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [87]:
arr_slice[:] = 64

In [88]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [101]:
c = arr[5:8].copy() #如果只想做副本而不是视图需要copy()函数

In [102]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [103]:
arr2d[2]

array([7, 8, 9])

In [104]:
arr2d[0,2]

3

In [109]:
arr2d [0][2] #与上面等价

3

In [110]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [111]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [113]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
old_values = arr3d[0].copy()

In [116]:
arr3d[0] =42

In [117]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [118]:
arr3d[0] = old_values

In [119]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [121]:
arr3d[1,0]

array([7, 8, 9])

In [122]:
x = arr3d[1]

In [123]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [124]:
x[0]

array([7, 8, 9])

In [125]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [126]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [127]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
arr2d[:2] #:表示横切默认从0开始 没有逗号

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
arr2d[:2,1:] #表示切第0行到第一行，第1列到第2列

array([[2, 3],
       [5, 6]])

In [131]:
arr2d[1,:2]

array([4, 5])

In [134]:
arr2d[:2,2]

array([3, 6])

In [137]:
arr2d[:,:1]# 表示索取第0列

array([[1],
       [4],
       [7]])

In [138]:
arr2d[:2,1:] = 0

In [139]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [153]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [179]:
data = np.random.randn(7,4)

In [155]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [180]:
data

array([[-0.25372786,  0.60945866, -0.89680796,  0.18221673],
       [ 1.79622818,  0.9350034 , -0.810179  ,  1.74312127],
       [ 0.11932303, -1.39216017,  1.44428069, -0.82136819],
       [ 1.78233643,  1.99107743,  0.11577483,  1.56536291],
       [-0.69446352,  0.90546438,  0.36226449,  0.31713428],
       [-1.82116868, -1.11355731,  1.33232751,  0.13508352],
       [ 0.26955816,  0.57851606, -0.07688586,  0.9789917 ]])

In [181]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [182]:
data[names == 'Bob']

array([[-0.25372786,  0.60945866, -0.89680796,  0.18221673],
       [ 1.78233643,  1.99107743,  0.11577483,  1.56536291]])

In [183]:
data[names == 'Bob', 2:]

array([[-0.89680796,  0.18221673],
       [ 0.11577483,  1.56536291]])

In [184]:
data[names == 'Bob', 3]

array([ 0.18221673,  1.56536291])

In [185]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [186]:
data[~(names == 'Bob')] #索引True值

array([[ 1.79622818,  0.9350034 , -0.810179  ,  1.74312127],
       [ 0.11932303, -1.39216017,  1.44428069, -0.82136819],
       [-0.69446352,  0.90546438,  0.36226449,  0.31713428],
       [-1.82116868, -1.11355731,  1.33232751,  0.13508352],
       [ 0.26955816,  0.57851606, -0.07688586,  0.9789917 ]])

In [187]:
cond = names == 'Bob'

In [188]:
data[~cond]

array([[ 1.79622818,  0.9350034 , -0.810179  ,  1.74312127],
       [ 0.11932303, -1.39216017,  1.44428069, -0.82136819],
       [-0.69446352,  0.90546438,  0.36226449,  0.31713428],
       [-1.82116868, -1.11355731,  1.33232751,  0.13508352],
       [ 0.26955816,  0.57851606, -0.07688586,  0.9789917 ]])

In [189]:
mask = (names == 'Bob') | (names == 'Will')

In [190]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [191]:
data[mask]

array([[-0.25372786,  0.60945866, -0.89680796,  0.18221673],
       [ 0.11932303, -1.39216017,  1.44428069, -0.82136819],
       [ 1.78233643,  1.99107743,  0.11577483,  1.56536291],
       [-0.69446352,  0.90546438,  0.36226449,  0.31713428]])

In [192]:
data[data < 0] = 0

In [193]:
data

array([[ 0.        ,  0.60945866,  0.        ,  0.18221673],
       [ 1.79622818,  0.9350034 ,  0.        ,  1.74312127],
       [ 0.11932303,  0.        ,  1.44428069,  0.        ],
       [ 1.78233643,  1.99107743,  0.11577483,  1.56536291],
       [ 0.        ,  0.90546438,  0.36226449,  0.31713428],
       [ 0.        ,  0.        ,  1.33232751,  0.13508352],
       [ 0.26955816,  0.57851606,  0.        ,  0.9789917 ]])

In [194]:
data[names != 'Joe'] = 7

In [195]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 1.79622818,  0.9350034 ,  0.        ,  1.74312127],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.        ,  1.33232751,  0.13508352],
       [ 0.26955816,  0.57851606,  0.        ,  0.9789917 ]])

In [202]:
arr = np.empty((8,4))

In [204]:
for i in range(8) :
    arr[i] = i

In [205]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [208]:
arr[[4,3,0,6,4]] #正数花式索引

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.]])

In [210]:
arr[[-3,-1,-7]] #负数索引

array([[ 5.,  5.,  5.,  5.],
       [ 7.,  7.,  7.,  7.],
       [ 1.,  1.,  1.,  1.]])

In [211]:
arr = np.arange(32).reshape((8,4))

In [212]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [214]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] #第一个是行值 第二个是列值

array([ 4, 23, 29, 10])

In [216]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]#第一个是行，换列

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [217]:
arr = np.arange(15).reshape((3, 5))

In [218]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [220]:
arr.T #转置

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [221]:
arr = np.random.randn(6, 3)

In [222]:
arr

array([[-1.18835174, -1.45305878,  0.24302662],
       [ 0.02444207, -0.40261133,  0.21988123],
       [ 0.81388175, -0.90681786, -2.66079538],
       [-0.87405029, -0.17942312,  0.85159585],
       [ 1.29875719,  0.44423892,  0.66513562],
       [-0.42073664, -0.41544238, -0.99208484]])

In [223]:
np.dot(arr.T, arr)

array([[ 4.70293427,  1.88743694, -1.91208104],
       [ 1.88743694,  3.49792759,  2.52603535],
       [-1.91208104,  2.52603535,  9.33909494]])

In [224]:
arr = np.arange(16).reshape((2, 2, 4))

In [225]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [226]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [227]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [228]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [229]:
arr = np.arange(10)

In [230]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [232]:
np.sqrt(arr) #对数组里面的数据进行开方

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [234]:
np.exp(arr)#取自然指数

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [235]:
x = np.random.randn(8)
y = np.random.randn(8)

In [236]:
x

array([ 1.18088662, -1.28755542, -0.62876309, -0.57391125,  0.09883894,
       -1.4027618 ,  1.48376871,  0.45982689])

In [237]:
y

array([-0.21888058,  0.1524784 , -0.11236921, -1.23736419, -1.25055693,
       -1.03301238,  0.33725967,  3.03768813])

In [240]:
np.maximum(x, y) #一一对比每个元素 取最大元素

array([ 1.18088662,  0.1524784 , -0.11236921, -0.57391125,  0.09883894,
       -1.03301238,  1.48376871,  3.03768813])

In [241]:
arr = np.random.randn(7) * 5

In [242]:
arr

array([ -5.14617634,  -5.82760869,  -3.81600386,   6.22896176,
        -3.16419421,   3.23391475,  12.64823937])

In [245]:
remainder, whole_part = np.modf(arr) #前面伟数组数据中的小数部分，后面为整数部分

In [244]:
remainder

array([-0.14617634, -0.82760869, -0.81600386,  0.22896176, -0.16419421,
        0.23391475,  0.64823937])

In [246]:
whole_part

array([ -5.,  -5.,  -3.,   6.,  -3.,   3.,  12.])

In [247]:
np.sqrt(arr)

C:\Users\LDP\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


array([        nan,         nan,         nan,  2.49578881,         nan,
        1.79830886,  3.55643633])

In [249]:
np.sqrt(arr,arr)

C:\Users\LDP\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


array([        nan,         nan,         nan,  2.49578881,         nan,
        1.79830886,  3.55643633])

In [250]:
arr

array([        nan,         nan,         nan,  2.49578881,         nan,
        1.79830886,  3.55643633])

In [251]:
points = np.arange(-5, 5, 0.01)

In [252]:
xs,ys = np.meshgrid(points,points)

In [253]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [254]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [255]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [256]:
import matplotlib.pyplot as plt

In [257]:
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()

In [258]:
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [259]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [260]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [261]:
cond = np.array([True, False, True, True, False])

In [262]:
result = [(x if c else y)
         for x ,y, c in zip(xarr,yarr,cond)]

In [263]:
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [264]:
result = np.where(cond,xarr,yarr)

In [265]:
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [266]:
arr = np.random.randn(4, 4)

In [267]:
arr

array([[-0.44375431,  0.45958132, -0.92588932,  0.50356977],
       [ 0.99039527,  1.50850643,  0.16764218, -0.1598824 ],
       [ 0.75797192,  1.96106908, -0.37018099,  0.12290316],
       [-0.38396291, -0.4123424 ,  0.31225421,  1.73317523]])

In [268]:
arr > 0 

array([[False,  True, False,  True],
       [ True,  True,  True, False],
       [ True,  True, False,  True],
       [False, False,  True,  True]], dtype=bool)

In [270]:
np.where(arr > 0 ,2,-2) # 用两个元素替换数组 True为正2 ，False为负2

array([[-2,  2, -2,  2],
       [ 2,  2,  2, -2],
       [ 2,  2, -2,  2],
       [-2, -2,  2,  2]])

In [271]:
np.where(arr > 0, 2, arr)# 用两个元素替换数组 True为正2 ，False为负2

array([[-0.44375431,  2.        , -0.92588932,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.1598824 ],
       [ 2.        ,  2.        , -0.37018099,  2.        ],
       [-0.38396291, -0.4123424 ,  2.        ,  2.        ]])

In [7]:
arr = np.random.randn(5, 4)

In [8]:
arr

array([[ 0.48651432, -0.61810775, -0.92464656, -2.21733428],
       [ 0.54806005,  0.91452424,  0.7799829 ,  0.58401731],
       [-1.01912242, -1.52975899,  0.67325238,  0.02399479],
       [-0.04911765,  0.20895178, -0.02753221,  0.78108634],
       [ 1.47309558,  0.07005566,  0.48348297,  0.94735194]])

In [9]:
arr.mean()

0.079437518743729271

In [10]:
np.mean(arr)

0.079437518743729271

In [11]:
arr.sum()

1.5887503748745855

In [12]:
arr.mean(axis=1) #计算行平均

array([-0.81839357,  0.70664612, -0.46290856,  0.22834706,  0.74349654])

In [13]:
arr.sum(axis=0)#计算列平均

array([ 1.43942987, -0.95433506,  0.98453947,  0.11911609])

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
arr.cumsum()#给前面元素累加

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [19]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7,8]])

In [20]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
arr.cumsum(axis=0) #按列累加

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [25]:
arr.cumprod(axis=1)#按行类乘

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [28]:
arr = np.random.randn(100)

In [29]:
arr

array([ 1.10486953, -0.20168054,  0.58767802, -0.65059881, -0.66725874,
       -0.53656536,  0.52971861,  0.06167665,  0.66046805,  1.63723254,
       -1.42514865, -1.21430164,  1.7584456 ,  2.27418792, -0.02945657,
       -1.37837187, -0.35855443, -0.48676052, -0.47646674, -0.59623274,
        1.54660162, -0.33154388, -1.02475215,  0.24790387,  1.84676244,
        0.27159563, -0.60771667, -1.33597653,  1.1030367 ,  0.30760163,
        1.16284937,  1.17357634,  0.51259818,  0.20775767,  2.87705685,
       -1.02671637, -0.28917503,  0.86221034, -0.25742978, -0.14615314,
        0.60951042,  1.83822612, -1.01264803,  0.92127563,  0.99196112,
       -0.81459031,  0.84663877,  0.13929463,  0.67253385,  0.82542282,
        1.80259928,  0.04632537, -0.1224636 , -0.98467231,  0.69524404,
        0.69207204, -0.14558443,  0.28480748, -0.3084528 ,  2.27261145,
        0.90421684, -1.67491573,  0.89459882, -3.23346068,  0.75710446,
       -1.5762852 , -1.11040102, -0.66005497, -0.78620187,  1.09

In [30]:
(arr > 0).sum()

54

In [31]:
bools = np.array([False, False, True, False])

In [33]:
bools.any() #只要有一个True就为真

True

In [35]:
bools.all()#所有元素都为True

False

In [36]:
arr = np.random.randn(6)

In [37]:
arr

array([ 0.76681158, -1.77186184, -0.04923311,  0.3145459 ,  0.13263367,
        0.4282414 ])

In [40]:
arr.sort()#冲小到大排序

In [39]:
arr

array([-1.77186184, -0.04923311,  0.13263367,  0.3145459 ,  0.4282414 ,
        0.76681158])

In [54]:
arr = np.random.randn(5, 3)

In [57]:
arr

array([[-2.09983701, -1.05764188, -0.13942794],
       [ 0.37800563,  1.59606902,  1.84298393],
       [-1.9228081 , -0.22553767,  0.04791776],
       [ 0.11714524,  1.61418278,  2.51747038],
       [-1.1133966 ,  1.00527667,  1.1518971 ]])

In [55]:
arr.sort(1)

In [56]:
arr

array([[-2.09983701, -1.05764188, -0.13942794],
       [ 0.37800563,  1.59606902,  1.84298393],
       [-1.9228081 , -0.22553767,  0.04791776],
       [ 0.11714524,  1.61418278,  2.51747038],
       [-1.1133966 ,  1.00527667,  1.1518971 ]])

In [58]:
large_arr = np.random.randn(1000)

In [59]:
large_arr.sort()

In [61]:
large_arr[int(0.05 * len(large_arr))] #求5%分位数

-1.6293006940973795

In [62]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [64]:
np.unique(names) #集合运算 找到数组中的唯一元素

array(['Bob', 'Joe', 'Will'],
      dtype='<U4')

In [65]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [66]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [68]:
np.in1d(values,[2,3,6])#一一验证每一个元素在不在后面的数组当中

array([ True, False, False,  True,  True, False,  True], dtype=bool)

In [69]:
arr = np.arange(10)

In [70]:
np.save('some_array', arr) #自动保存成.npy文件

In [71]:
np.load('some_array.npy') #读取数据

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.savez('array_archive.npz', a=arr, b=arr) #将两个数组压缩成字典

In [77]:
arch = np.load('array_archive.npz') #读取磁盘数据

In [78]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.savez_compressed('arrays_compressed.npz', a=arr,b=arr)

In [80]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [83]:
y = np.array([[6.,23.],[-1,7],[8,9]])

In [84]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [85]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [86]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [88]:
np.dot(x,y) #矩阵的乘法 与上面等价

array([[  28.,   64.],
       [  67.,  181.]])

In [89]:
np.dot(x, np.ones(3))

array([  6.,  15.])

In [92]:
x @ np.ones(3) #与上面等价

array([  6.,  15.])

In [93]:
from numpy.linalg import inv, qr

In [94]:
X = np.random.randn(5, 5)

In [95]:
mat = X.T.dot(X)

In [100]:
inv(mat) #矩阵求逆

array([[  99.92443114,   37.84355842,  -18.94772258,   32.76006899,
         114.14600754],
       [  37.84355842,   15.73765843,   -6.18155771,   12.77325269,
          43.18297053],
       [ -18.94772258,   -6.18155771,    5.16866658,   -5.80545868,
         -21.51613357],
       [  32.76006899,   12.77325269,   -5.80545868,   11.06546537,
          37.47585414],
       [ 114.14600754,   43.18297053,  -21.51613357,   37.47585414,
         130.79854497]])

In [101]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   0.00000000e+00,   1.42108547e-14,
         -1.42108547e-14,  -5.68434189e-14],
       [  7.10542736e-15,   1.00000000e+00,   0.00000000e+00,
          1.06581410e-14,   4.26325641e-14],
       [  0.00000000e+00,   1.06581410e-14,   1.00000000e+00,
         -5.32907052e-15,  -3.55271368e-14],
       [ -7.10542736e-15,  -3.55271368e-15,  -1.77635684e-15,
          1.00000000e+00,   0.00000000e+00],
       [ -5.68434189e-14,  -2.84217094e-14,   7.10542736e-15,
          1.42108547e-14,   1.00000000e+00]])

In [102]:
q, r = qr(mat)

In [105]:
r

array([[ -5.91667520e+00,   1.39665121e+00,  -1.75316177e+00,
          1.20311478e+00,   4.07333804e+00],
       [  0.00000000e+00,  -1.67510538e+00,   4.12041196e-01,
          3.28400201e+00,  -3.19004070e-01],
       [  0.00000000e+00,   0.00000000e+00,  -1.23332824e+00,
          3.48319812e+00,  -1.20381796e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         -1.62909084e+00,   4.68116325e-01],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   5.43368149e-03]])

In [106]:
samples = np.random.normal(size=(4, 4))

In [107]:
samples

array([[ 0.81087696, -1.16404365, -0.59598268,  0.25404726],
       [ 1.10328923,  1.55847858, -1.39244901, -0.43154253],
       [-1.70843193,  0.33981381, -0.25052445, -0.73616447],
       [-1.42397241, -0.72109392,  0.76261654, -1.25536438]])

In [108]:
from random import normalvariate

In [109]:
N = 1000000

In [110]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

1 loop, best of 3: 2 s per loop


In [111]:
%timeit np.random.normal(size=N)

10 loops, best of 3: 72.1 ms per loop


In [112]:
np.random.seed(1234)

In [113]:
rng = np.random.RandomState(1234)

In [115]:
rng.randn(10) #创建⼀个与其它隔离的随机数⽣成器

array([ 1.15003572,  0.99194602,  0.95332413, -2.02125482, -0.33407737,
        0.00211836,  0.40545341,  0.28909194,  1.32115819, -1.54690555])

In [124]:
import random
from matplotlib import pyplot as plt
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

In [125]:
plt.plot(walk[:100])

In [126]:
nsteps = 1000

In [127]:
draws = np.random.randint(0, 2, size=nsteps)

In [128]:
steps = np.where(draws > 0, 1, -1)

In [129]:
walk = steps.cumsum()

In [130]:
walk.min()

-9

In [131]:
walk.max()

60

In [132]:
(np.abs(walk) >= 10).argmax()

297

In [133]:
nwalks = 5000

In [134]:
nsteps = 1000

In [135]:
draws = np.random.randint(0, 2, size=(nwalks, nsteps))

In [136]:
steps = np.where(draws > 0, 1, -1)

In [139]:
walks = steps.cumsum(1)#按列累加

In [138]:
walks

array([[  1,   2,   3, ...,  46,  47,  46],
       [  1,   0,   1, ...,  40,  41,  42],
       [  1,   2,   3, ..., -26, -27, -28],
       ..., 
       [  1,   0,   1, ...,  64,  65,  66],
       [  1,   2,   1, ...,   2,   1,   0],
       [ -1,  -2,  -3, ...,  32,  33,  34]], dtype=int32)

In [140]:
walks.max()

122

In [141]:
walk.min()

-9

In [142]:
hits30 = (np.abs(walks) >= 30).any(1)

In [143]:
hits30

array([ True,  True,  True, ...,  True, False,  True], dtype=bool)

In [144]:
hits30.sum()

3368

In [145]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)

In [146]:
crossing_times.mean()

509.99762470308787

In [148]:
steps = np.random.normal(loc=0, scale=0.25, size=(nwalks, nsteps))